INSERT INTO logs34 (
    team_id,
    original_expiry_timestamp,
    uuid,
    trace_id,
    span_id,
    trace_flags,
    timestamp,
    observed_timestamp,
    body,
    severity_text,
    severity_number,
    service_name,
    resource_attributes,
    instrumentation_scope,
    event_name,
    attributes_map_str,
    _partition,
    _topic,
    _offset,
    _bytes_uncompressed,
    _bytes_compressed,
    _record_count
)
WITH
    number AS n,
    toDateTime64({bench_start:String}, 6, 'UTC') + toIntervalSecond(n % 86400) + toIntervalMicrosecond(intDiv(n, 86400) % 1000000) AS ts,
    concat('svc-', toString(n % 64)) AS service,
    concat('pod-', toString(n % 256)) AS pod,
    concat('host-', toString(n % 1024)) AS host,
    arrayElement(['us-east', 'us-west', 'eu-central', 'ap-south'], (n % 4) + 1) AS region,
    arrayElement(['prod', 'staging', 'dev'], (n % 3) + 1) AS env,
    if(n % 2 = 0, 'logfmt', 'json') AS fmt,
    if(n % 97 = 0, 'error', if(n % 19 = 0, 'warn', if(n % 7 = 0, 'debug', 'info'))) AS sev,
    if(sev = 'error', 17, if(sev = 'warn', 13, if(sev = 'debug', 5, 9))) AS sevnum,
    arrayElement(['/checkout', '/login', '/search', '/api/items', '/health'], (n % 5) + 1) AS route,
    if(n % 97 = 0, '500', if(n % 23 = 0, '404', '200')) AS status,
    toString(5 + (n % 2000)) AS duration_ms,
    toString(128 + (n % 8192)) AS size_b,
    if(
        fmt = 'logfmt',
        concat('level=', sev, ' service=', service, ' env=', env, ' region=', region, ' pod=', pod, ' route=', route, ' status=', status, ' duration=', duration_ms, 'ms size=', size_b, 'B request_id=req-', toString(n), if(n % 97 = 0, ' error=true message=checkout_failed', ' message=ok')),
        concat('{"level":"', sev, '","service":"', service, '","env":"', env, '","region":"', region, '","pod":"', pod, '","route":"', route, '","status":', status, ',"duration":', duration_ms, ',"size":', size_b, ',"message":"', if(n % 97 = 0, 'checkout error', 'ok'), '"}')
    ) AS line
SELECT
    {tenant:Int32},
    ts + toIntervalDay(30),
    concat('bench:', toString(n)),
    concat('trace-', toString(n % 100000)),
    concat('span-', toString(n % 100000)),
    0,
    ts,
    ts,
    line,
    sev,
    sevnum,
    service,
    map('service.name', service, 'host.hostname', host, 'region', region),
    '',
    '',
    map('app__str', 'snuffle-bench', 'env__str', env, 'region__str', region, 'format__str', fmt, 'pod__str', pod, 'host__str', host, 'route__str', route, 'status__str', status, 'duration__str', duration_ms, 'size__str', size_b, 'detected_level__str', sev),
    0,
    'snuffle-perf',
    n,
    length(line),
    length(line),
    1
FROM numbers({rows:UInt64})
SETTINGS max_insert_threads = 4;
